#!/bin/bash
#nslookup is a program to query Internet domain name servers
#nsloolup [option] [IP address or Domain name] [DNS server address]
#Interactive mode -> query name servers for information about various hosts

nslookup who.int 8.8.8.8
