#!/bin/bash
#Find the service which makes it possible to run specific tasks following a regular schedule
#cron -> daemon to execute scheduled commands (Vixie Cron)
#Use ctontab to open the cron table for editing
#The cron table is the list of tasks scheduled to run at regular time

cron
